### ISSUE TITLE
Enhance main page for datagraft

### ISSUE THREAD

**Issue by nvnikolov** [dapaas/dapaas.github.io#6]
- [x] change logo with "BETA" sign
- [x] change screenshots on the first page
- [x] refactor header and footer
  - [x] remove side menu on the header
  - [x] move documentation links to the left side of the footer
- [x] use smaller font size for main text (looks a bit too big for the text boxes right now)
- [x] transition between hash links in the page
  - [x] make it smooth
  - [x] add separators between screens with new hash links to go to the next screen
- [x] change accent color to fit the datagraft theme

**Comment by nvnikolov** [comment]
Also change the text color to rgb(232, 235, 245)

**Comment by ayymanduh** [comment]
- The arrow on the landing page (https://datagraft.net/) is wonky underneath the front page text.
- It should read 'up to' not upto on the publish page (https://datagraft.net/pages/publish/)
- Terms of use, privacy policy and cookies policy all link to the DaPaaS project page documentation - separate documentation for the DataGraft platform needs to be there instead.
- Change footer text: add "the" before DaPaaS and change the "," to go after the word project
- User should be able to change their password under account management (https://datagraft.net/pages/myaccount.jsp)
